export const ALL_TASK_REQUEST = "ALL_TASK__REQUEST";
export const ALL_TASK_SUCCESS = "ALL_TASK__SUCCESS";
export const ALL_TASK_FAIL = "ALL_TASK__FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER__FAIL";

export const DASHBORAD_SUCCESS = "DASHBORAD_SUCCESS";
export const DASHBORAD_REQUEST = "DASHBORAD_REQUEST";

export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";

export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";

export const SEARCH_TASK_SUCCESS = "SEARCH_TASK_SUCCESS";

export const   UPDATE_TASK_SUCCESS
 = "UPDATE_TASK_SUCCESS";